<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="1" total="4" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="POM_PageFactory_TestNG" duration-ms="22316" started-at="2014-10-16T05:36:00Z" finished-at="2014-10-16T05:36:22Z">
    <groups>
    </groups>
    <test name="LoginTest" duration-ms="22114" started-at="2014-10-16T05:36:00Z" finished-at="2014-10-16T05:36:22Z">
      <class name="com.qtpselenim.testcases.LoginTest">
        <test-method status="FAIL" signature="loginTest(java.util.Hashtable)[pri:0, instance:com.qtpselenim.testcases.LoginTest@c3eed5]" name="loginTest" duration-ms="15867" started-at="2014-10-15T22:36:00Z" data-provider="getLoginData" finished-at="2014-10-15T22:36:16Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Username=mekonecbsflyid@gmail.com, Data_Flag=N, Password=elements12, Runmode=Y}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Could NOT login expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Could NOT login expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.qtpselenim.testcases.LoginTest.loginTest(LoginTest.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="loginTest(java.util.Hashtable)[pri:0, instance:com.qtpselenim.testcases.LoginTest@c3eed5]" name="loginTest" duration-ms="5922" started-at="2014-10-15T22:36:16Z" data-provider="getLoginData" finished-at="2014-10-15T22:36:22Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Username=mekonecbsflyid@gmail.com, Data_Flag=Y, Password=elements1, Runmode=Y}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="SKIP" signature="findFriend()[pri:0, instance:com.qtpselenim.testcases.LoginTest@c3eed5]" name="findFriend" duration-ms="1" started-at="2014-10-15T22:36:22Z" depends-on-methods="com.qtpselenim.testcases.LoginTest.loginTest" finished-at="2014-10-15T22:36:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- findFriend -->
      </class> <!-- com.qtpselenim.testcases.LoginTest -->
    </test> <!-- LoginTest -->
    <test name="UPloadPicTest" duration-ms="6" started-at="2014-10-16T05:36:22Z" finished-at="2014-10-16T05:36:22Z">
      <class name="com.qtpselenim.testcases.LoginTest">
        <test-method status="PASS" signature="init()[pri:0, instance:com.qtpselenim.testcases.LoginTest@c3eed5]" name="init" is-config="true" duration-ms="13119" started-at="2014-10-15T22:35:47Z" finished-at="2014-10-15T22:36:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
      </class> <!-- com.qtpselenim.testcases.LoginTest -->
      <class name="com.qtpselenim.testcases.UploadPic">
        <test-method status="SKIP" signature="UploadPic()[pri:0, instance:com.qtpselenim.testcases.UploadPic@12b7e8c]" name="UploadPic" duration-ms="4" started-at="2014-10-15T22:36:22Z" finished-at="2014-10-15T22:36:22Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test
	at com.qtpselenim.testcases.UploadPic.UploadPic(UploadPic.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UploadPic -->
      </class> <!-- com.qtpselenim.testcases.UploadPic -->
    </test> <!-- UPloadPicTest -->
  </suite> <!-- POM_PageFactory_TestNG -->
</testng-results>
